export const iPhoneModels =  [
  {
    name: 'iPhone 1',
    image: 'https://www.3nions.com/wp-content/uploads/2021/01/1st-iPhone.jpeg',
    details: {
      camera: '2MP without video recording',
      RAM: 'Not specified',
      storage: '4GB, 8GB',
      battery: 'Not specified',
      processor: '412 MHz ARM 11',
      otherDetails: [
        'Revolutionized the smartphone industry',
        'Intuitive touch interface',
        'App Store introduced third-party applications',
        'Screen Size: 3.5 inches',
        'Release Year: 2007',
      ],
    },
    cons: [
      'No 3G connectivity',
      'Limited camera capabilities',
      'Limited storage options',
      'Non-expandable storage',
      'Limited app selection compared to current standards',
    ],
  },
  {
    name: 'iPhone 3G',
    image: 'https://www.3nions.com/wp-content/uploads/2021/01/iPhone-3G.jpeg',
    details: {
      camera: 'No video recording',
      RAM: 'Not specified',
      storage: '8GB, 16GB',
      battery: 'Not specified',
      processor: '412 MHz ARM 11',
      otherDetails: [
        'Introduction of 3G connectivity',
        'App Store growth with more applications',
        'GPS functionality added',
        'Plastic back was less durable',
        'Limited multitasking capabilities',
        'Screen Size: 3.5 inches',
        'Release Year: 2008',
      ],
    },
    cons: [
      'No video recording',
      'Plastic back prone to scratches',
      'Limited multitasking capabilities',
      'No front-facing camera',
      'Limited app selection compared to current standards',
    ],
  },
  {
    name: 'iPhone 3GS',
    image: 'https://www.3nions.com/wp-content/uploads/2021/01/iPhone-3GS.jpeg',
    details: {
      camera: '3.2 MP camera with autofocus',
      RAM: 'Not specified',
      storage: '8GB, 16GB',
      battery: 'Enhanced battery life',
      processor: 'Not specified',
      otherDetails: [
        'Improved performance with faster processor',
        'Introduction of video recording capability',
        'Voice Control feature added',
        'Enhanced battery life',
        'Available in 8GB and 16GB storage options',
      ],
    },
    cons: [
      'Limited multitasking capabilities',
      'No front-facing camera',
      'No Retina display',
      'Released with iOS 3, limited app compatibility over time',
      'No support for the latest iOS versions',
    ],
  },
  {
    name: 'iPhone 4',
    image: 'https://www.3nions.com/wp-content/uploads/2021/01/iPhone-4.jpeg',
    details: {
      camera: '5MP rear camera with HD video recording',
      RAM: 'Not specified',
      storage: '8GB, 16GB, 32GB',
      battery: 'Not specified',
      processor: 'Apple A4',
      otherDetails: [
        'New design with glass front and back',
        'Retina Display for crisp visuals',
        'Front-facing camera for video calls',
        'Introduction of FaceTime for video calls',
        'iOS 4 with multitasking support',
        'Screen Size: 3.5 inches',
        'Release Year: 2010',
      ],
    },
    cons: [
      'Antenna issues (Death Grip)',
      'Limited customization compared to some Android devices',
      'No 4G/LTE connectivity',
      'Non-expandable storage',
      'Smaller screen size by modern standards',
    ],
  },
  {
    name: 'iPhone 5',
    image: 'https://www.3nions.com/wp-content/uploads/2021/01/iPhone-5-i.jpeg',
    details: {
      camera: 'Improved front-facing camera',
      RAM: 'Not specified',
      storage: '16GB, 32GB, 64GB',
      battery: 'Not specified',
      processor: 'Apple A6',
      otherDetails: [
        'Taller 4-inch Retina Display',
        'Lightning connector introduced',
        'Thinner and lighter design',
        'iOS 6 with Apple Maps introduction',
        '4G/LTE connectivity for faster data speeds',
        'Screen Size: 4 inches',
        'Release Year: 2012',
      ]
    },
    cons: [
      'Scuff-prone aluminum body',
      'Limited design innovation compared to previous models',
      'Lightning connector required new accessories',
      'iOS 6 Maps app had initial inaccuracies',
      'Non-expandable storage',
      'Battery life shorter than some competitors',
      'No wireless charging support',
      'Smaller screen size by modern standards',
      'No significant camera improvements',
      'No NFC for contactless payments',
    ],
  },
  {
    name: 'iPhone 6',
    image: 'https://www.3nions.com/wp-content/uploads/2021/01/iPhone-6.jpeg',
    details: {
      camera: '8MP rear camera with optical image stabilization',
      RAM: 'Not specified',
      storage: '16GB, 64GB, 128GB',
      battery: 'Not specified',
      processor: 'Apple A8',
      otherDetails: [
        'Larger 4.7-inch Retina HD display',
        'Slimmer and rounded design',
        'Introduction of the Apple Pay feature',
        'Improved Touch ID fingerprint sensor',
        'iOS 8 with Health app and Continuity features',
        'Screen Size: 4.7 inches',
        'Release Year: 2014',
      ],
    },
    cons: [
      'Bendgate controversy (some devices reported bending)',
      'Limited design innovation compared to previous models',
      'Non-expandable storage',
      'No significant camera improvements compared to iPhone 5S',
      'No 4K video recording support',
      'Battery life shorter than some competitors',
      'No wireless charging support',
      'Non-removable battery',
      'No water or dust resistance',
      'Lightning connector required new accessories',
    ],
  },
  {
    name: 'iPhone 7',
    image: 'https://www.3nions.com/wp-content/uploads/2021/01/iPhone-7.jpeg',
    details: {
      camera: 'Improved 12MP rear camera with optical image stabilization',
      RAM: 'Not specified',
      storage: '32GB, 128GB, 256GB',
      battery: 'Not specified',
      processor: 'Apple A10 Fusion',
      otherDetails: [
        'Introduction of the dual-camera system on iPhone 7 Plus',
        'Water and dust resistance with IP67 rating',
        'Removal of the 3.5mm headphone jack',
        'Home button replaced with a solid-state, pressure-sensitive button',
        'Quad-core A10 Fusion chip for improved performance',
        'iOS 10 with new features like Raise to Wake',
        'Screen Size: 4.7 inches',
        'Release Year: 2016',
      ],
    },
    cons: [
      'Removal of the 3.5mm headphone jack was controversial',
      'Design similar to previous models',
      'Non-expandable storage',
      'No significant improvement in display resolution',
      'No wireless charging support',
      'Non-removable battery',
      'Limited design innovation compared to previous models',
      'No fast charging out of the box',
      'High starting price',
      'Limited customization compared to some Android devices',
    ],
  },
  {
    name: 'iPhone 8',
    image: 'https://www.3nions.com/wp-content/uploads/2021/01/iPhone-8.jpeg',
    details: {
      camera: '12MP rear camera with larger and faster sensor',
      RAM: 'Not specified',
      storage: '64GB, 256GB',
      battery: 'Not specified',
      processor: 'Apple A11 Bionic',
      otherDetails: [
        'Glass back for wireless charging',
        'Introduction of True Tone display technology',
        'A11 Bionic chip for improved performance',
        'iOS 11 with augmented reality (AR) capabilities',
        'Retains the traditional Home button with Touch ID',
        'Screen Size: 4.7 inches',
        'Release Year: 2017',
      ],
    },
    cons: [
      'Design similar to previous models',
      'No significant improvement in display resolution',
      'Non-expandable storage',
      'No dual-camera system like the iPhone 8 Plus',
      'No Face ID, still relies on Touch ID',
      'Non-removable battery',
      'Limited design innovation compared to previous models',
      'No 3.5mm headphone jack',
      'High starting price',
      'Limited customization compared to some Android devices',
    ],
  },
  {
    name: 'iPhone 8 Plus',
    image: 'https://www.3nions.com/wp-content/uploads/2021/01/iPhone-8-Plus.jpeg',
    details: {
      camera: 'Dual 12MP rear cameras with larger and faster sensors',
      RAM: 'Not specified',
      storage: '64GB, 256GB',
      battery: 'Not specified',
      processor: 'Apple A11 Bionic',
      otherDetails: [
        'Larger 5.5-inch Retina HD display',
        'Glass back for wireless charging',
        'A11 Bionic chip for improved performance',
        'iOS 11 with augmented reality (AR) capabilities',
        'Retains the traditional Home button with Touch ID',
        'Screen Size: 5.5 inches',
        'Release Year: 2017',
      ],
    },
    cons: [
      'Design similar to previous Plus models',
      'No significant improvement in display resolution',
      'Non-expandable storage',
      'No Face ID, still relies on Touch ID',
      'Non-removable battery',
      'Limited design innovation compared to previous models',
      'No 3.5mm headphone jack',
      'High starting price',
      'Limited customization compared to some Android devices',
    ],
  },
  {
    name: 'iPhone X',
    image: 'https://www.3nions.com/wp-content/uploads/2021/01/iPhone-X.jpeg',
    details: {
      camera: 'Dual 12MP rear cameras with optical image stabilization',
      RAM: 'Not specified',
      storage: '64GB, 256GB',
      battery: 'Not specified',
      processor: 'Apple A11 Bionic',
      otherDetails: [
        'Introduction of the Super Retina display with OLED technology',
        'Removal of the Home button, introducing Face ID for authentication',
        'Stainless steel frame with glass back for wireless charging',
        'A11 Bionic chip with Neural Engine for AI capabilities',
        'iOS 11 with Animoji and augmented reality (AR) features',
        'Screen Size: 5.8 inches',
        'Release Year: 2017',
      ],
    },
    cons: [
      'High starting price',
      'No 3.5mm headphone jack',
      'Non-expandable storage',
      'Limited customization compared to some Android devices',
      'Fragile glass back',
      'No fingerprint scanner (reliant on Face ID)',
      'Limited availability of third-party accessories due to design changes',
      'Incremental improvements over previous models',
      'Initial shortage due to high demand',
      'Limited availability of Face ID in certain scenarios',
    ],
  },
  {
    name: 'iPhone XS',
    image: 'https://www.3nions.com/wp-content/uploads/2021/01/iPhone-XS.jpeg',
    details: {
      camera: 'Dual 12MP rear cameras with Smart HDR and adjustable bokeh',
      RAM: 'Not specified',
      storage: '64GB, 256GB, 512GB',
      battery: 'Not specified',
      processor: 'Apple A12 Bionic',
      otherDetails: [
        'Continuation of the Super Retina display with OLED technology',
        'Stainless steel frame with glass back for wireless charging',
        'A12 Bionic chip with Neural Engine for enhanced AI capabilities',
        'iOS 12 with Memoji and Screen Time features',
        'Introduction of Gold color option',
        'Screen Size: 5.8 inches',
        'Release Year: 2018',
      ],
    },
    cons: [
      'High starting price',
      'No 3.5mm headphone jack',
      'Non-expandable storage',
      'Incremental improvements over iPhone X',
      'Fragile glass back',
      'No significant design changes compared to iPhone X',
      'Limited customization compared to some Android devices',
      'Incremental camera improvements over iPhone X',
      'Incremental performance improvements over iPhone X',
      'Incremental improvements in battery life',
    ],
  },
  {
    name: 'iPhone XS Max',
    image: 'https://www.3nions.com/wp-content/uploads/2021/01/iPhone-XS-Max.jpeg',
    details: {
      camera: 'Dual 12MP rear cameras with Smart HDR and adjustable bokeh',
      RAM: 'Not specified',
      storage: '64GB, 256GB, 512GB',
      battery: 'Not specified',
      processor: 'Apple A12 Bionic',
      otherDetails: [
        'Largest iPhone display at the time with a 6.5-inch Super Retina display',
        'Stainless steel frame with glass back for wireless charging',
        'A12 Bionic chip with Neural Engine for enhanced AI capabilities',
        'iOS 12 with Memoji and Screen Time features',
        'Introduction of Gold color option',
        'Screen Size: 6.5 inches',
        'Release Year: 2018',
      ],
    },
    cons: [
      'High starting price',
      'No 3.5mm headphone jack',
      'Non-expandable storage',
      'Incremental improvements over iPhone X',
      'Fragile glass back',
      'No significant design changes compared to iPhone X',
      'Limited customization compared to some Android devices',
      'Incremental camera improvements over iPhone X',
      'Incremental performance improvements over iPhone X',
      'Incremental improvements in battery life',
    ],
  },
  {
    name: 'iPhone 11',
    image: 'https://www.3nions.com/wp-content/uploads/2021/01/iPhone-11.jpeg',
    details: {
      camera: 'Dual 12MP ultra-wide and wide cameras with Night mode',
      RAM: 'Not specified',
      storage: '64GB, 128GB, 256GB',
      battery: 'Not specified',
      processor: 'Apple A13 Bionic',
      otherDetails: [
        'Liquid Retina display with LCD technology',
        'Aluminum and glass design for wireless charging',
        'A13 Bionic chip with improved machine learning capabilities',
        'iOS 13 with Dark Mode and Sign in with Apple',
        'Six color options: White, Black, Green, Yellow, Purple, Red',
        'Screen Size: 6.1 inches',
        'Release Year: 2019',
      ],
    },
    cons: [
      'Lower resolution display compared to Pro models',
      'Thicker bezels compared to Pro models',
      'No telephoto lens for optical zoom',
      'No Night mode for the front camera',
      'Aluminum frame instead of stainless steel',
      'Non-expandable storage',
      'No 512GB storage option',
      'Limited customization compared to some Android devices',
      'No 3D Touch feature',
      'Incremental improvements over previous models',
    ],
  },
  {
    name: 'iPhone 12',
    image: 'https://www.3nions.com/wp-content/uploads/2021/01/iPhone-12.jpeg',
    details: {
      camera: 'Dual 12MP ultra-wide and wide cameras with Night mode',
      RAM: 'Not specified',
      storage: '64GB, 128GB, 256GB',
      battery: 'Not specified',
      processor: 'Apple A14 Bionic',
      otherDetails: [
        'Super Retina XDR display with Ceramic Shield for durability',
        'Ceramic Shield and Glass design for wireless charging',
        'A14 Bionic chip with improved machine learning capabilities',
        'iOS 14 with App Library and Widgets',
        'Five color options: White, Black, Green, Blue, (PRODUCT)RED',
        'Screen Size: 6.1 inches',
        'Release Year: 2020',
      ],
    },
    cons: [
      'No high-refresh-rate ProMotion display',
      'Thicker and heavier compared to iPhone 12 mini',
      'Non-expandable storage',
      'Limited customization compared to some Android devices',
      'No 512GB storage option',
      'Incremental improvements over previous models',
      'No 3D Touch feature',
      'No telephoto lens for optical zoom',
      'Limited Night mode functionality compared to Pro models',
      'No LiDAR scanner',
    ],
  },
  {
    name: 'iPhone 12 Mini',
    image: 'https://www.3nions.com/wp-content/uploads/2021/01/iPhone-12-mini-image.jpeg',
    details: {
      camera: 'Dual 12MP ultra-wide and wide cameras with Night mode',
      RAM: 'Not specified',
      storage: '64GB, 128GB, 256GB',
      battery: 'Not specified',
      processor: 'Apple A14 Bionic',
      otherDetails: [
        'Super Retina XDR display with Ceramic Shield for durability',
        'Ceramic Shield and Glass design for wireless charging',
        'A14 Bionic chip with improved machine learning capabilities',
        'iOS 14 with App Library and Widgets',
        'Five color options: White, Black, Green, Blue, (PRODUCT)RED',
        'Screen Size: 5.4 inches',
        'Release Year: 2020',
      ],
    },
    cons: [
      'Smaller display size may not suit all users',
      'Thicker and heavier compared to iPhone SE (2nd generation)',
      'Non-expandable storage',
      'Limited customization compared to some Android devices',
      'No 512GB storage option',
      'Incremental improvements over previous models',
      'No 3D Touch feature',
      'No telephoto lens for optical zoom',
      'Limited Night mode functionality compared to Pro models',
      'No LiDAR scanner',
    ],
  },
  {
    name: 'iPhone 12 Pro',
    image: 'https://www.3nions.com/wp-content/uploads/2021/01/iPhone-12-pro.jpeg',
    details: {
      camera: 'Triple 12MP ultra-wide, wide, and telephoto cameras with Night mode',
      RAM: 'Not specified',
      storage: '128GB, 256GB, 512GB',
      battery: 'Not specified',
      processor: 'Apple A14 Bionic',
      otherDetails: [
        'Super Retina XDR display with Ceramic Shield for durability',
        'Ceramic Shield and Stainless Steel design for wireless charging',
        'A14 Bionic chip with improved machine learning capabilities',
        'iOS 14 with App Library and Widgets',
        'Four color options: Graphite, Silver, Gold, Pacific Blue',
        'Screen Size: 6.1 inches',
        'Release Year: 2020',
      ],
    },
    cons: [
      'No 120Hz ProMotion display',
      'Thicker and heavier compared to iPhone 12',
      'Non-expandable storage',
      'Limited customization compared to some Android devices',
      'No 1TB storage option',
      'Incremental improvements over previous models',
      'No LiDAR scanner on the iPhone 12 Pro',
      'High starting price',
      'Limited Night mode functionality compared to Pro Max model',
      'No reverse wireless charging',
    ],
  },
  {
    name: 'iPhone 12 Pro Max',
    image: 'https://www.3nions.com/wp-content/uploads/2021/01/iPhone-12-Pro-Max.jpeg',
    details: {
      camera: 'Triple 12 MP, 12 MP, 12 MP, TOF 3D LiDAR scanner (depth)',
      RAM: '6 GB',
      storage: '128GB, 256GB, 512GB',
      battery: 'Non-removable Li-Ion 3687 mAh battery',
      processor: 'A14 Bionic chip with 6-core CPU, 4-core GPU, and 16-core Neural Engine',
      otherDetails: [
        '6.7 inches Super Retina XDR OLED, HDR10, Dolby Vision',
        'iOS 14, upgradable to the latest version',
        '5G capable',
        'Water and dust resistant (IP68)',
      ],
    },
    cons: [
      'No 120Hz ProMotion display',
      'Largest and heaviest iPhone, may not suit all users',
      'Non-expandable storage',
      'Limited customization compared to some Android devices',
      'No 1TB storage option',
      'Incremental improvements over previous models',
      'No LiDAR scanner on the iPhone 12 Pro Max',
      'High starting price',
      'Limited Night mode functionality compared to Pro models',
      'No reverse wireless charging',
    ],
  },
  {
    name: 'iPhone 13',
    image: 'https://www.3nions.com/wp-content/uploads/2021/01/iPhone-13-1.jpeg',
    details: {
      camera: 'Triple 12MP ultra-wide, wide, and telephoto cameras with Night mode',
      RAM: 'Not specified',
      storage: '128GB, 256GB, 512GB',
      battery: 'Not specified',
      processor: 'Apple A14 Bionic',
      otherDetails: [
        'Super Retina XDR display with Ceramic Shield for durability',
        'Ceramic Shield and Stainless Steel design for wireless charging',
        'A14 Bionic chip with improved machine learning capabilities',
        'iOS 14 with App Library and Widgets',
        'Four color options: Graphite, Silver, Gold, Pacific Blue',
        'Screen Size: 6.7 inches',
        'Release Year: 2020',
      ],
    },
    cons: [
      'No high-refresh-rate ProMotion display',
      'Non-expandable storage',
      'Limited customization compared to some Android devices',
      'Incremental improvements over previous models',
      'No significant design changes compared to iPhone 12',
      'No reverse wireless charging',
      'No LiDAR scanner',
      'High starting price',
      'Limited Night mode functionality compared to Pro models',
      'Incremental improvements in battery life',
    ],
  },
  {
    name: 'iPhone 13 Pro',
    image: 'https://www.3nions.com/wp-content/uploads/2021/01/iPhone-13-Pro-1.jpeg',
    details: {
      camera: 'Dual 12MP ultra-wide and wide cameras with Night mode',
      RAM: 'Not specified',
      storage: '128GB, 256GB, 512GB, 1TB',
      battery: 'Not specified',
      processor: 'Apple A15 Bionic',
      otherDetails: [
        'Super Retina XDR display with Ceramic Shield for durability',
        'Ceramic Shield and Glass design for wireless charging',
        'A15 Bionic chip with improved machine learning capabilities',
        'iOS 15 with Focus and Live Text features',
        'Five color options: Pink, Blue, Midnight, Starlight, (PRODUCT)RED',
        'Screen Size: 6.1 inches',
        'Release Year: 2021',
      ],
    },
    cons: [
      'No USB-C port, still uses Lightning',
      'Non-expandable storage',
      'Limited customization compared to some Android devices',
      'Incremental improvements over previous models',
      'No reverse wireless charging',
      'High starting price',
      'Limited Night mode functionality compared to Pro Max model',
      'Incremental improvements in battery life',
      'No significant design changes compared to iPhone 12 Pro',
      'No significant camera improvements compared to iPhone 12 Pro',
    ],
  },
  {
    name: 'iPhone 13 Pro Max',
    image: 'https://www.3nions.com/wp-content/uploads/2021/01/iPhone-13-Pro-Max.jpeg',
    details: {
      camera: 'Triple 12MP ultra-wide, wide, and telephoto cameras with Night mode',
      RAM: 'Not specified',
      storage: '128GB, 256GB, 512GB, 1TB',
      battery: 'Not specified',
      processor: 'Apple A15 Bionic',
      otherDetails: [
        'Super Retina XDR display with ProMotion technology',
        'Ceramic Shield and Stainless Steel design for wireless charging',
        'A15 Bionic chip with improved machine learning capabilities',
        'iOS 15 with Focus and Live Text features',
        'Four color options: Graphite, Gold, Silver, Sierra Blue',
        'Screen Size: 6.7 inches',
        'Release Year: 2021',
      ],
    },
    cons: [
      'No USB-C port, still uses Lightning',
      'Non-expandable storage',
      'Limited customization compared to some Android devices',
      'Incremental improvements over previous models',
      'No reverse wireless charging',
      'High starting price',
      'Limited Night mode functionality compared to Pro model',
      'Incremental improvements in battery life',
      'No significant design changes compared to iPhone 12 Pro Max',
      'No significant camera improvements compared to iPhone 12 Pro Max',
    ],
  }
]