export const iPhoneModels =  [
  {
    name: 'iPhone 1',
    image: 'https://www.3nions.com/wp-content/uploads/2021/01/1st-iPhone.jpeg',
    details: [
      'Revolutionized the smartphone industry',
      'Intuitive touch interface',
      'App Store introduced third-party applications',
      '2MP camera without video recording',
      'Screen Size: 3.5 inches',
      'Processor: 412 MHz ARM 11',
      'Storage Options: 4GB, 8GB',
      'Release Year: 2007',
    ],
    cons: [
      'No 3G connectivity',
      'Limited camera capabilities',
      'Limited storage options',
      'Non-expandable storage',
      'Limited app selection compared to current standards',
    ],
  },
  {
    name: 'iPhone 3G',
    image: 'https://www.3nions.com/wp-content/uploads/2021/01/iPhone-3G.jpeg',
    details: [
      'Introduction of 3G connectivity',
      'App Store growth with more applications',
      'GPS functionality added',
      'No video recording',
      'Plastic back was less durable',
      'Limited multitasking capabilities',
      'Screen Size: 3.5 inches',
      'Processor: 412 MHz ARM 11',
      'Storage Options: 8GB, 16GB',
      'Release Year: 2008',
    ],
    cons: [
      'No video recording',
      'Plastic back prone to scratches',
      'Limited multitasking capabilities',
      'No front-facing camera',
      'Limited app selection compared to current standards',
    ],
  },
  {
    name: 'iPhone 3GS',
    image: 'https://www.3nions.com/wp-content/uploads/2021/01/iPhone-3GS.jpeg',
    details: [
      'Improved performance with faster processor',
      'Introduction of video recording capability',
      'Voice Control feature added',
      '3.2 MP camera with autofocus',
      'Enhanced battery life',
      'Available in 8GB and 16GB storage options',
    ],
    cons: [
      'Limited multitasking capabilities',
      'No front-facing camera',
      'No Retina display',
      'Released with iOS 3, limited app compatibility over time',
      'No support for the latest iOS versions',
    ],
  },
  {
    name: 'iPhone 4',
    image: 'https://www.3nions.com/wp-content/uploads/2021/01/iPhone-4.jpeg',
    details: [
      'New design with glass front and back',
      'Retina Display for crisp visuals',
      'Front-facing camera for video calls',
      '5MP rear camera with HD video recording',
      'Introduction of FaceTime for video calls',
      'iOS 4 with multitasking support',
      'Screen Size: 3.5 inches',
      'Processor: Apple A4',
      'Storage Options: 8GB, 16GB, 32GB',
      'Release Year: 2010',
    ],
    cons: [
      'Antenna issues (Death Grip)',
      'Limited customization compared to some Android devices',
      'No 4G/LTE connectivity',
      'Non-expandable storage',
      'Smaller screen size by modern standards',
    ],
  },
  {
    name: 'iPhone 5',
    image: 'https://www.3nions.com/wp-content/uploads/2021/01/iPhone-5-i.jpeg',
    details: [
      'Taller 4-inch Retina Display',
      'Lightning connector introduced',
      'Thinner and lighter design',
      'Improved front-facing camera',
      'iOS 6 with Apple Maps introduction',
      '4G/LTE connectivity for faster data speeds',
      'Screen Size: 4 inches',
      'Processor: Apple A6',
      'Storage Options: 16GB, 32GB, 64GB',
      'Release Year: 2012',
    ],
    cons: [
      'Scuff-prone aluminum body',
      'Limited design innovation compared to previous models',
      'Lightning connector required new accessories',
      'iOS 6 Maps app had initial inaccuracies',
      'Non-expandable storage',
      'Battery life shorter than some competitors',
      'No wireless charging support',
      'Smaller screen size by modern standards',
      'No significant camera improvements',
      'No NFC for contactless payments',
    ],
  },
  {
    name: 'iPhone 6',
    image: 'https://www.3nions.com/wp-content/uploads/2021/01/iPhone-6.jpeg',
    details: [
      'Larger 4.7-inch Retina HD display',
      'Slimmer and rounded design',
      'Introduction of the Apple Pay feature',
      'Improved Touch ID fingerprint sensor',
      '8MP rear camera with optical image stabilization',
      'iOS 8 with Health app and Continuity features',
      'Screen Size: 4.7 inches',
      'Processor: Apple A8',
      'Storage Options: 16GB, 64GB, 128GB',
      'Release Year: 2014',
    ],
    cons: [
      'Bendgate controversy (some devices reported bending)',
      'Limited design innovation compared to previous models',
      'Non-expandable storage',
      'No significant camera improvements compared to iPhone 5S',
      'No 4K video recording support',
      'Battery life shorter than some competitors',
      'No wireless charging support',
      'Non-removable battery',
      'No water or dust resistance',
      'Lightning connector required new accessories',
    ],
  },
  {
    name: 'iPhone 7',
    image: 'https://www.3nions.com/wp-content/uploads/2021/01/iPhone-7.jpeg',
    details: [
      'Introduction of the dual-camera system on iPhone 7 Plus',
      'Water and dust resistance with IP67 rating',
      'Removal of the 3.5mm headphone jack',
      'Home button replaced with a solid-state, pressure-sensitive button',
      'Improved 12MP rear camera with optical image stabilization',
      'Quad-core A10 Fusion chip for improved performance',
      'iOS 10 with new features like Raise to Wake',
      'Screen Size: 4.7 inches',
      'Processor: Apple A10 Fusion',
      'Storage Options: 32GB, 128GB, 256GB',
      'Release Year: 2016',
    ],
    cons: [
      'Removal of the 3.5mm headphone jack was controversial',
      'Design similar to previous models',
      'Non-expandable storage',
      'No significant improvement in display resolution',
      'No wireless charging support',
      'Non-removable battery',
      'Limited design innovation compared to previous models',
      'No fast charging out of the box',
      'High starting price',
      'Limited customization compared to some Android devices',
    ],
  },
  {
    name: 'iPhone 8',
    image: 'https://www.3nions.com/wp-content/uploads/2021/01/iPhone-8.jpeg',
    details: [
      'Glass back for wireless charging',
      'Introduction of True Tone display technology',
      'A11 Bionic chip for improved performance',
      '12MP rear camera with larger and faster sensor',
      'iOS 11 with augmented reality (AR) capabilities',
      'Retains the traditional Home button with Touch ID',
      'Screen Size: 4.7 inches',
      'Processor: Apple A11 Bionic',
      'Storage Options: 64GB, 256GB',
      'Release Year: 2017',
    ],
    cons: [
      'Design similar to previous models',
      'No significant improvement in display resolution',
      'Non-expandable storage',
      'No dual-camera system like the iPhone 8 Plus',
      'No Face ID, still relies on Touch ID',
      'Non-removable battery',
      'Limited design innovation compared to previous models',
      'No 3.5mm headphone jack',
      'High starting price',
      'Limited customization compared to some Android devices',
    ],
  },
  {
    name: 'iPhone 8 Plus',
    image: 'https://www.3nions.com/wp-content/uploads/2021/01/iPhone-8-Plus.jpeg',
    details: [
      'Larger 5.5-inch Retina HD display',
      'Dual-camera system for optical zoom and Portrait mode',
      'Glass back for wireless charging',
      'A11 Bionic chip for improved performance',
      '12MP dual rear cameras with larger and faster sensors',
      'iOS 11 with augmented reality (AR) capabilities',
      'Retains the traditional Home button with Touch ID',
      'Screen Size: 5.5 inches',
      'Processor: Apple A11 Bionic',
      'Storage Options: 64GB, 256GB',
      'Release Year: 2017',
    ],
    cons: [
      'Design similar to previous Plus models',
      'No significant improvement in display resolution',
      'Non-expandable storage',
      'No Face ID, still relies on Touch ID',
      'Non-removable battery',
      'Limited design innovation compared to previous models',
      'No 3.5mm headphone jack',
      'High starting price',
      'Limited customization compared to some Android devices',
    ],
  },
  {
    name: 'iPhone X',
    image: 'https://www.3nions.com/wp-content/uploads/2021/01/iPhone-X.jpeg',
    details: [
      'Introduction of the Super Retina display with OLED technology',
      'Removal of the Home button, introducing Face ID for authentication',
      'Stainless steel frame with glass back for wireless charging',
      'Dual 12MP rear cameras with optical image stabilization',
      'A11 Bionic chip with Neural Engine for AI capabilities',
      'iOS 11 with Animoji and augmented reality (AR) features',
      'Screen Size: 5.8 inches',
      'Processor: Apple A11 Bionic',
      'Storage Options: 64GB, 256GB',
      'Release Year: 2017',
    ],
    cons: [
      'High starting price',
      'No 3.5mm headphone jack',
      'Non-expandable storage',
      'Limited customization compared to some Android devices',
      'Fragile glass back',
      'No fingerprint scanner (reliant on Face ID)',
      'Limited availability of third-party accessories due to design changes',
      'Incremental improvements over previous models',
      'Initial shortage due to high demand',
      'Limited availability of Face ID in certain scenarios',
    ],
  },
  {
    name: 'iPhone XS',
    image: 'https://www.3nions.com/wp-content/uploads/2021/01/iPhone-XS.jpeg',
    details: [
      'Continuation of the Super Retina display with OLED technology',
      'Stainless steel frame with glass back for wireless charging',
      'Dual 12MP rear cameras with Smart HDR and adjustable bokeh',
      'A12 Bionic chip with Neural Engine for enhanced AI capabilities',
      'iOS 12 with Memoji and Screen Time features',
      'Introduction of Gold color option',
      'Screen Size: 5.8 inches',
      'Processor: Apple A12 Bionic',
      'Storage Options: 64GB, 256GB, 512GB',
      'Release Year: 2018',
    ],
    cons: [
      'High starting price',
      'No 3.5mm headphone jack',
      'Non-expandable storage',
      'Incremental improvements over iPhone X',
      'Fragile glass back',
      'No significant design changes compared to iPhone X',
      'Limited customization compared to some Android devices',
      'Incremental camera improvements over iPhone X',
      'Incremental performance improvements over iPhone X',
      'Incremental improvements in battery life',
    ],
  },
  {
    name: 'iPhone XS Max',
    image: 'https://www.3nions.com/wp-content/uploads/2021/01/iPhone-XS-Max.jpeg',
    details: [
      'Largest iPhone display at the time with a 6.5-inch Super Retina display',
      'Stainless steel frame with glass back for wireless charging',
      'Dual 12MP rear cameras with Smart HDR and adjustable bokeh',
      'A12 Bionic chip with Neural Engine for enhanced AI capabilities',
      'iOS 12 with Memoji and Screen Time features',
      'Introduction of Gold color option',
      'Screen Size: 6.5 inches',
      'Processor: Apple A12 Bionic',
      'Storage Options: 64GB, 256GB, 512GB',
      'Release Year: 2018',
    ],
    cons: [
      'High starting price',
      'No 3.5mm headphone jack',
      'Non-expandable storage',
      'Incremental improvements over iPhone X',
      'Fragile glass back',
      'No significant design changes compared to iPhone X',
      'Limited customization compared to some Android devices',
      'Incremental camera improvements over iPhone X',
      'Incremental performance improvements over iPhone X',
      'Incremental improvements in battery life',
    ],
  },
  {
    name: 'iPhone 11',
    image: 'https://www.3nions.com/wp-content/uploads/2021/01/iPhone-11.jpeg',
    details: [
      'Liquid Retina display with LCD technology',
      'Aluminum and glass design for wireless charging',
      'Dual 12MP ultra-wide and wide cameras with Night mode',
      'A13 Bionic chip with improved machine learning capabilities',
      'iOS 13 with Dark Mode and Sign in with Apple',
      'Six color options: White, Black, Green, Yellow, Purple, Red',
      'Screen Size: 6.1 inches',
      'Processor: Apple A13 Bionic',
      'Storage Options: 64GB, 128GB, 256GB',
      'Release Year: 2019',
    ],
    cons: [
      'Lower resolution display compared to Pro models',
      'Thicker bezels compared to Pro models',
      'No telephoto lens for optical zoom',
      'No Night mode for the front camera',
      'Aluminum frame instead of stainless steel',
      'Non-expandable storage',
      'No 512GB storage option',
      'Limited customization compared to some Android devices',
      'No 3D Touch feature',
      'Incremental improvements over previous models',
    ],
  },
  {
    name: 'iPhone 12',
    image: 'https://www.3nions.com/wp-content/uploads/2021/01/iPhone-12.jpeg',
    details: [
      'Super Retina XDR display with Ceramic Shield for durability',
      'Ceramic Shield and Glass design for wireless charging',
      'Dual 12MP ultra-wide and wide cameras with Night mode',
      'A14 Bionic chip with improved machine learning capabilities',
      'iOS 14 with App Library and Widgets',
      'Five color options: White, Black, Green, Blue, (PRODUCT)RED',
      'Screen Size: 6.1 inches',
      'Processor: Apple A14 Bionic',
      'Storage Options: 64GB, 128GB, 256GB',
      'Release Year: 2020',
    ],
    cons: [
      'No high-refresh-rate ProMotion display',
      'Thicker and heavier compared to iPhone 12 mini',
      'Non-expandable storage',
      'Limited customization compared to some Android devices',
      'No 512GB storage option',
      'Incremental improvements over previous models',
      'No 3D Touch feature',
      'No telephoto lens for optical zoom',
      'Limited Night mode functionality compared to Pro models',
      'No LiDAR scanner',
    ],
  },
  {
    name: 'iPhone 12 Mini',
    image: 'https://www.3nions.com/wp-content/uploads/2021/01/iPhone-12-mini-image.jpeg',
    details: [
      'Super Retina XDR display with Ceramic Shield for durability',
      'Ceramic Shield and Glass design for wireless charging',
      'Dual 12MP ultra-wide and wide cameras with Night mode',
      'A14 Bionic chip with improved machine learning capabilities',
      'iOS 14 with App Library and Widgets',
      'Five color options: White, Black, Green, Blue, (PRODUCT)RED',
      'Screen Size: 5.4 inches',
      'Processor: Apple A14 Bionic',
      'Storage Options: 64GB, 128GB, 256GB',
      'Release Year: 2020',
    ],
    cons: [
      'Smaller display size may not suit all users',
      'Thicker and heavier compared to iPhone SE (2nd generation)',
      'Non-expandable storage',
      'Limited customization compared to some Android devices',
      'No 512GB storage option',
      'Incremental improvements over previous models',
      'No 3D Touch feature',
      'No telephoto lens for optical zoom',
      'Limited Night mode functionality compared to Pro models',
      'No LiDAR scanner',
    ],
  },
  {
    name: 'iPhone 12 Pro',
    image: 'https://www.3nions.com/wp-content/uploads/2021/01/iPhone-12-pro.jpeg',
    details: [
      'Super Retina XDR display with Ceramic Shield for durability',
      'Ceramic Shield and Stainless Steel design for wireless charging',
      'Triple 12MP ultra-wide, wide, and telephoto cameras with Night mode',
      'A14 Bionic chip with improved machine learning capabilities',
      'iOS 14 with App Library and Widgets',
      'Four color options: Graphite, Silver, Gold, Pacific Blue',
      'Screen Size: 6.1 inches',
      'Processor: Apple A14 Bionic',
      'Storage Options: 128GB, 256GB, 512GB',
      'Release Year: 2020',
    ],
    cons: [
      'No 120Hz ProMotion display',
      'Thicker and heavier compared to iPhone 12',
      'Non-expandable storage',
      'Limited customization compared to some Android devices',
      'No 1TB storage option',
      'Incremental improvements over previous models',
      'No LiDAR scanner on the iPhone 12 Pro',
      'High starting price',
      'Limited Night mode functionality compared to Pro Max model',
      'No reverse wireless charging',
    ],
  },
  {
    name: 'iPhone 12 Pro Max',
    image: 'https://www.3nions.com/wp-content/uploads/2021/01/iPhone-12-Pro-Max.jpeg',
    details: [
      'Super Retina XDR display with Ceramic Shield for durability',
      'Ceramic Shield and Stainless Steel design for wireless charging',
      'Triple 12MP ultra-wide, wide, and telephoto cameras with Night mode',
      'A14 Bionic chip with improved machine learning capabilities',
      'iOS 14 with App Library and Widgets',
      'Four color options: Graphite, Silver, Gold, Pacific Blue',
      'Screen Size: 6.7 inches',
      'Processor: Apple A14 Bionic',
      'Storage Options: 128GB, 256GB, 512GB',
      'Release Year: 2020',
    ],
    cons: [
      'No 120Hz ProMotion display',
      'Largest and heaviest iPhone, may not suit all users',
      'Non-expandable storage',
      'Limited customization compared to some Android devices',
      'No 1TB storage option',
      'Incremental improvements over previous models',
      'No LiDAR scanner on the iPhone 12 Pro Max',
      'High starting price',
      'Limited Night mode functionality compared to Pro models',
      'No reverse wireless charging',
    ],
  },
  {
    name: 'iPhone 13',
    image: 'https://www.3nions.com/wp-content/uploads/2021/01/iPhone-13-1.jpeg',
    details: [
      'Super Retina XDR display with Ceramic Shield for durability',
      'Ceramic Shield and Glass design for wireless charging',
      'Dual 12MP ultra-wide and wide cameras with Night mode',
      'A15 Bionic chip with improved machine learning capabilities',
      'iOS 15 with Focus and Live Text features',
      'Five color options: Pink, Blue, Midnight, Starlight, (PRODUCT)RED',
      'Screen Size: 6.1 inches',
      'Processor: Apple A15 Bionic',
      'Storage Options: 128GB, 256GB, 512GB, 1TB',
      'Release Year: 2021',
    ],
    cons: [
      'No high-refresh-rate ProMotion display',
      'Non-expandable storage',
      'Limited customization compared to some Android devices',
      'Incremental improvements over previous models',
      'No significant design changes compared to iPhone 12',
      'No reverse wireless charging',
      'No LiDAR scanner',
      'High starting price',
      'Limited Night mode functionality compared to Pro models',
      'Incremental improvements in battery life',
    ],
  },
  {
    name: 'iPhone 13 Pro',
    image: 'https://www.3nions.com/wp-content/uploads/2021/01/iPhone-13-Pro-1.jpeg',
    details: [
      'Super Retina XDR display with ProMotion technology',
      'Ceramic Shield and Stainless Steel design for wireless charging',
      'Triple 12MP ultra-wide, wide, and telephoto cameras with Night mode',
      'A15 Bionic chip with improved machine learning capabilities',
      'iOS 15 with Focus and Live Text features',
      'Four color options: Graphite, Gold, Silver, Sierra Blue',
      'Screen Size: 6.1 inches',
      'Processor: Apple A15 Bionic',
      'Storage Options: 128GB, 256GB, 512GB, 1TB',
      'Release Year: 2021',
    ],
    cons: [
      'No USB-C port, still uses Lightning',
      'Non-expandable storage',
      'Limited customization compared to some Android devices',
      'Incremental improvements over previous models',
      'No reverse wireless charging',
      'High starting price',
      'Limited Night mode functionality compared to Pro Max model',
      'Incremental improvements in battery life',
      'No significant design changes compared to iPhone 12 Pro',
      'No significant camera improvements compared to iPhone 12 Pro',
    ],
  },
  {
    name: 'iPhone 13 Pro Max',
    image: 'https://www.3nions.com/wp-content/uploads/2021/01/iPhone-13-Pro-Max.jpeg',
    details: [
      'Super Retina XDR display with ProMotion technology',
      'Ceramic Shield and Stainless Steel design for wireless charging',
      'Triple 12MP ultra-wide, wide, and telephoto cameras with Night mode',
      'A15 Bionic chip with improved machine learning capabilities',
      'iOS 15 with Focus and Live Text features',
      'Four color options: Graphite, Gold, Silver, Sierra Blue',
      'Screen Size: 6.7 inches',
      'Processor: Apple A15 Bionic',
      'Storage Options: 128GB, 256GB, 512GB, 1TB',
      'Release Year: 2021',
    ],
    cons: [
      'No USB-C port, still uses Lightning',
      'Non-expandable storage',
      'Limited customization compared to some Android devices',
      'Incremental improvements over previous models',
      'No reverse wireless charging',
      'High starting price',
      'Limited Night mode functionality compared to Pro model',
      'Incremental improvements in battery life',
      'No significant design changes compared to iPhone 12 Pro Max',
      'No significant camera improvements compared to iPhone 12 Pro Max',
    ],
  }
]